### ISSUE TITLE
TypeScript: why does waitFor expect Promise<void>?

### ISSUE THREAD

**Issue by huwmartin** [hoverinc/playwright-testing-library#238]
A question about something which might be a bug: `waitFor` expects to be called with an expectation function which returns `void | Promise<void>`, I can see this is coming from `wait-for-expect`. However, in the examples included in the playwright-testing-library docs it demonstrates using `waitFor` like so:

```
await waitFor(() => getByText($document, 'Loading...'))
```

I'd quite like to use it like this, too! But at the moment this results in a type-error `Type 'Promise<ElementHandle>' is not assignable to type 'void | Promise<void>'` because `getByText` promise resolves to an `ElementHandle`.

What is the recommended usage of `waitFor` with TypeScript? Or do the type defs for `waitFor` need to be updated? Happy to help with this :)

**Comment by jrolfs** [comment]
Hi @huwmartin, thanks for pointing that out! With the current documentation, this does sound like a bug, however I think the addition of the `findBy*` queries makes the documented use case redundant. Since **wait-for-expect** essentially discards the return value of the `callback`, I think it makes sense to keep the current definitions so that's clear.

I think the recommended usage for the example you cited from the readme would be the following:

```ts
await findByText($document, 'Loading...')
```

Now, `waitFor` is still available for more specific use cases, however you'd want to ensure not to return anything. One way to do so would be to simply add braces to your callback. Another would be to wrap your assertion in `expect()`, which is the intended use case of **wait-for-expect**:

```ts
await waitFor(() => {
  getByText($document, 'Loading...')
})
```

or

```ts
await waitFor(() => expect(getByText($document, 'Loading...')).toBeTruthy())
```

Ultimately, I think this is a documentation issue, but I'm curious whether the above alternatives fit your use case. If so, I think it's just a matter of figuring out exactly how we want to update the documentation to make sure the above information is included or implied. If it turns out we need to support the use case of returning an `ElementHandle` from `waitFor`, then I think we have a bit of work to do and I'm not sure **wait-for-expect** is the bet fit there. 

Let me know what you think!

**Comment by huwmartin** [comment]
Thanks for the reply @jrolfs! That makes total sense to me, any of the described approaches would work fine 👍 The main [testing-library docs](https://testing-library.com/docs/dom-testing-library/api-async/) do a good job of including explicit examples for both `findBy*` and `waitFor` (and seems to favour wrapping the assertion in an `expect()` in the docs), so I think that could be quite instructive.

**Comment by jrolfs** [comment]
Sounds good! Good call on referencing the **testing-library** docs, I think we should strive for consistency there wherever possible. I'll take a crack at updating the readme when I get a chance, but that might not be until later this week. I'd be more than happy to review a PR if you find yourself with time for that 😉.
