### ISSUE TITLE
Implementation of byRole queries is incorrect.

### ISSUE THREAD

**Issue by aaron-nance** [hoverinc/playwright-testing-library#349]
According to the [Testing Library documentation](https://testing-library.com/docs/queries/byrole), the byRole queries should return elements based on their [default role](https://www.w3.org/TR/html-aria/#docconformance). 

For example, if I my DOM has header tags (h1,h2, etc), queryAllByRole(container, 'header'), should return all the header elements in the container, but instead always returns an empty array. I have tried to get this work with several different tags and their default roles and all have failed. 

For example, if I run the following in Jest I get the expected results:
```
const articleCount = await rendered.queryAllByRole('article');
console.log( `article count = ${articleCount.length}`)
```

But the equivalent in Playwright using this library, the returned array is always empty:
```
const root = await page.locator(ROOT_SEL);
const itemArticles = await queryAllByRole(root, 'article');
console.log( `items articles length = ${itemArticles.length}`);
```

The byRole queries should be using the accessibility tree to determine roles, but they appear to just be using the "role" attribute on a tag.

**Comment by jrolfs** [comment]
Hi, thanks for filing an issue. I think the problem here is that you’re passing a `Locator` to the query instead of an `ElementHandle`. We’re current discussing how we might better support the Playwright APIs that work with locators. I think supporting this case would be fairly straightforward, but the query would still return `ElementHandle` instances for the time being.

I will make sure that we have test coverage for the default role stuff and add some clarification around the `Locator` vs. `ElementHandle` stuff to the documentation. The `Locator` APIs were added after this library was originally created.

**Comment by aaron-nance** [comment]
Thanks for getting back to me! I'm closing this. I just realized I was making a dumb mistake. The queries are working fine with the locator, but it really helps when you're doing your queries to make sure that what you're querying is on the visible tab on the page. D'oh!

**Comment by jrolfs** [comment]
Thanks for the update. It's good to know that they do, in fact, work with a `Locator` instance. I wonder if it's worth trying to warn or provide better feedback for the case that you're describing there (elements are not visible).

**Comment by jrolfs** [comment]
Ah, I just also wanted to mention that if you are looking for more support in the `Locator` deparment, we have been talking a bit about supporting them better. For now I think you can probably just track #330, though maybe I should open an issue to track that as well.
